# Generated by Django 3.2.23 on 2024-02-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('auth_code', models.TextField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.CharField(choices=[('FYERS', 'FYERS'), ('ZERODHA', 'ZERODHA'), ('ANGEL_ONE', 'ANGEL_ONE'), ('GROWW', 'GROWW'), ('UPSTOX', 'UPSTOX')], default='FYERS', max_length=10)),
            ],
        ),
    ]
