# Generated by Django 3.2.23 on 2024-02-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='auth_code',
            new_name='access_token',
        ),
    ]
